### ISSUE TITLE
Invalid resource for DELETE action

### ISSUE THREAD

**Issue by soumGh** [jbachelet/ocapi-settings-with-ease#1]
For delete action
`/custom_objects/*` is an invalid resource. 

`/custom_objects/*/*` works.

**Comment by jbachelet** [comment]
Thank you @soumGh to bring this up!

The app had an issue with the regexp that replaces the paths dynamic values with `*`. This is now fixed.

For example:
`/custom_objects/{object_type}/{key}` was transformed with `/custom_objects/*` instead of `/custom_objects/*/*`.

Enjoy this tool :rocket:
